name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --ignore-scripts
      - name: Lint & format
        run: npm run lint && npm run check:format
      - name: Validate data schema
        run: npm run check:schema
      - name: Build site
        run: npm run build

  e2e:
    runs-on: ubuntu-latest
    needs: build-and-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --ignore-scripts
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Serve built site
        run: npx http-server -p 8000 dist &
      - name: Run e2e tests
        run: npx -y wait-on http://127.0.0.1:8000 && npx playwright test

  lighthouse:
    runs-on: ubuntu-latest
    needs: build-and-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --ignore-scripts
      - name: Serve built site
        run: npx http-server -p 8000 dist &
      - name: Run Lighthouse CI
        run: npx -y wait-on http://127.0.0.1:8000 && npx -y @lhci/cli autorun --config=.lighthouserc.json

  links:
    runs-on: ubuntu-latest
    needs: build-and-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --ignore-scripts
      - name: Serve built site
        run: npx http-server -p 8000 dist &
      - name: Check links
        run: npx -y wait-on http://127.0.0.1:8000 && npm run check:links
